### ISSUE TITLE
Issue with the Trainer-Financial marketing assesment

### ISSUE THREAD

**Issue by karthik-istar** [ISTARSkills/AppIssues#1]
When we launch the assessment it is directly redirecting us to END OF SESSION slide, none of the questions are visible in the session. The assessment is present in the ISTAR -Trainer-Assessment-Financial and Accounting Analysis batch group.
![screenshot_2016-11-16-15-54-34](https://cloud.githubusercontent.com/assets/21259158/20346021/e9ecdfea-ac1f-11e6-92fb-c5b5b9ee06f2.png)

**Comment by mayank-istar** [comment]
can u check and close.
